//
//  Ty_DatabaseDefine_AttentionAndFans.h
//  腾云家务
//
//  Created by Xu Zhao on 14-6-4.
//  Copyright (c) 2014年 齐 浩. All rights reserved.
//

#ifndef _____Ty_DatabaseDefine_AttentionAndFans_h
#define _____Ty_DatabaseDefine_AttentionAndFans_h

//时间戳表
#define TIMEFRAME @"TIMEFRAME"
#define TIMEFRAME_TABLE_NAME @"TIMEFRAME_TABLE_NAME"
#define TIMEFRAME_TABLE_TIME @"TIMEFRAME_TABLE_TIME"

//我的关注 && 我的粉丝
#define CONTACTDATA @"CONTACTDATA"

#define CONTACTDATA_ID @"CONTACTDATA_ID"
#define CONTACTDATA_ATTENTION_USER_GUID @"CONTACTDATA_ATTENTION_USER_GUID"//我关注的人
#define CONTACTDATA_FANS_USER_GUID @"CONTACTDATA_FANS_USER_GUID"//关注我的人
#define CONTACTDATA_USER_NAME @"CONTACTDATA_USER_NAME"//联系人姓名
#define CONTACTDATA_USER_SPELL @"CONTACTDATA_USER_SPELL"//联系人拼音
#define CONTACTDATA_USER_COMPANY @"CONTACTDATA_USER_COMPANY"//联系人公司
#define CONTACTDATA_INTERMEDIARY_NAME @"CONTACTDATA_INTERMEDIARY_NAME"//联系人所属公司
#define CONTACTDATA_USER_PHOTO @"CONTACTDATA_USER_PHOTO"//联系人头像
#define CONTACTDATA_USER_BIG_PHOTO @"CONTACTDATA_USER_BIG_PHOTO"//联系人大头像
#define CONTACTDATA_USER_TAG @"CONTACTDATA_USER_TAG"//联系人标签
#define CONTACTDATA_USER_TYPE @"CONTACTDATA_USER_TYPE"//联系人类型
#define CONTACTDATA_USER_SEX @"CONTACTDATA_USER_SEX"//联系人性别
#define CONTACTDATA_USER_REALNAME @"CONTACTDATA_USER_REALNAME"//联系人真实姓名
#define CONTACTDATA_USER_EVALUATEMASTER @"CONTACTDATA_USER_EVALUATEMASTER"
#define CONTACTDATA_USER_EVALUATEEMPLOYEE @"CONTACTDATA_USER_EVALUATEEMPLOYEE"
#define CONTACTDATA_ANNEAR @"CONTACTDATA_ANNEAR"
#define CONTACTDATA_USER_ADDRESS @"CONTACTDATA_USER_ADDRESS"//联系人地址
#define CONTACTDATA_LNG @"CONTACTDATA_LNG"//联系人坐标
#define CONTACTDATA_LAT @"CONTACTDATA_LAT"//联系人坐标
#define CONTACTDATA_USER_SERVE_QUALITY @"CONTACTDATA_USER_SERVE_QUALITY"
#define CONTACTDATA_USER_SERVE_ATTITUDE @"CONTACTDATA_USER_SERVE_ATTITUDE"
#define CONTACTDATA_USER_SERVE_SPEED @"CONTACTDATA_USER_SERVE_SPEED"
#define CONTACTDATA_DETAIL_IDCARD @"CONTACTDATA_DETAIL_IDCARD"
#define CONTACTDATA_DETAIL_RECORD @"CONTACTDATA_DETAIL_RECORD"
#define CONTACTDATA_DETAIL_CENSUS @"CONTACTDATA_DETAIL_CENSUS"
#define CONTACTDATA_USER_SERVE_SIZE @"CONTACTDATA_USER_SERVE_SIZE"
#define CONTACTDATA_USER_POST @"CONTACTDATA_USER_POST"//联系人职业

#endif
