//
//  Ty_DatabaseDefine_Order.h
//  腾云家务
//
//  Created by lgs on 14-6-4.
//  Copyright (c) 2014年 齐 浩. All rights reserved.
//

#ifndef _____Ty_DatabaseDefine_Order_h
#define _____Ty_DatabaseDefine_Order_h

//需求详情表

#define REQUIREMENT @"REQUIREMENT"

#define REQUIREMENT_GUID @"REQUIREMENT_GUID"//需求的guid

#define REQUIREMENT_NUMBER @"REQUIREMENT_NUMBER"//需求编号

#define REQUIREMENT_STAGE @"REQUIREMENT_STAGE"//需求的状态

#define REQUIREMENT_TYPE @"REQUIREMENT_TYPE"//需求的类型

#define REQUIREMENT_USER_TYPE @"REQUIREMENT_USER_TYPE"//当前用户的类型

#define REQUIREMENT_CANDIDATE_STATUS @"REQUIREMENT_CANDIDATE_STATUS"//应征状态，0未应征

#define REQUIREMENT_EVALUATE_STAGE @"REQUIREMENT_EVALUATE_STAGE"//评价状态

#define REQUIREMENT_WORK_GUID @"REQUIREMENT_WORK_GUID"//工种的guid

#define REQUIREMENT_WORK_NAME @"REQUIREMENT_WORK_NAME"//工种的名字

#define REQUIREMENT_PUBLISH_USERGUID @"REQUIREMENT_PUBLISH_USERGUID"//发布人的guid

#define REQUIREMENT_PUBLISH_USERNAME @"REQUIREMENT_PUBLISH_USERNAME"//发布人的userName

#define REQUIREMENT_PUBLISH_USERREALNAME @"REQUIREMENT_PUBLISH_USERREALNAME"//发布人的真实姓名

#define REQUIREMENT_PUBLISH_USERSEX @"REQUIREMENT_PUBLISH_USERSEX"//发布人的性别

#define REQUIREMENT_PUBLISH_USERTYPE @"REQUIREMENT_PUBLISH_USERTYPE"//发布人的类型

#define REQUIREMENT_PUBLISH_USERPHOTO @"REQUIREMENT_PUBLISH_USERPHOTO"//发布人头像地址

#define REQUIREMENT_PUBLISH_USEREVALUATE @"REQUIREMENT_PUBLISH_USEREVALUATE"//发布人的星级

#define REQUIREMENT_PUBLISH_USER_ANNEAR @"REQUIREMENT_PUBLISH_USER_ANNEAR"//发布人的锤炼号

#define REQUIRELMENT_ADDRESS @"REQUIRELMENT_ADDRESS"//所在区域

#define REQUIRELMENT_ADDRESS_DETAIL @"REQUIRELMENT_ADDRESS_DETAIL"//详细地址

#define REQUIREMENT_PUBLISH_TIME @"REQUIREMENT_PUBLISH_TIME"//发布时间

#define REQUIREMENT_START_TIME @"REQUIREMENT_START_TIME"//开始时间

#define REQUIREMENT_END_TIME @"REQUIREMENT_END_TIME"//结束时间

#define REQUIREMENT_PRICE_UNIT @"REQUIREMENT_PRICE_UNIT"//单价

#define REQUIREMENT_PAY_STAGE @"REQUIREMENT_PAY_STAGE"//支付状态

#define REQUIREMENT_DEAL_PRICE @"REQUIREMENT_DEAL_PRICE"//最后成交价格

#define REQUIREMENT_WORK_AMOUNT @"REQUIREMENT_WORK_AMOUNT"//工作总量

#define REQUIREMENT_CONNECT_NAME @"REQUIREMENT_CONNECT_NAME"//联系人姓名

#define REQUIREMENT_CONECT_IPHONE @"REQUIREMENT_CONECT_IPHONE"//联系人电话

#define REQUIREMENT_ASK_PRICE @"REQUIREMENT_ASK_PRICE"//价格要求

#define REQUIREMENT_ASK_AGE @"REQUIREMENT_ASK_AGE"//年龄要求

#define REQUIREMENT_ASK_SEX @"REQUIREMENT_ASK_SEX"//性别要求

#define REQUIREMENT_ASK_EDUCATION @"REQUIREMENT_ASK_EDUCATION"//学历要求

#define REQUIREMENT_ASK_NATION @"REQUIREMENT_ASK_NATION"//民族要求

#define REQUIREMENT_ASK_EXPERIENCE @"REQUIREMENT_ASK_EXPERIENCE"//工作经验要求

#define REQUIREMENT_ASK_CENSUS @"REQUIREMENT_ASK_CENSUS"//籍贯要求

#define REQUIREMENT_ASK_OTHER @"REQUIREMENT_ASK_OTHER"//其他要求

#define REQUIREMENT_OLD_ORDER_USER_REALNAME @"REQUIREMENT_OLD_ORDER_USER_REALNAME"//之前预约人的真实姓名


#define REQUIREMENT_UPDATE_TIME @"REQUIREMENT_UPDATE_TIME"//最后的更新时间

//预约人的相关信息
#define ORDER_PERSON @"ORDER_PERSON"

#define ORDER_PERSON_ID @"ORDER_PERSON_ID"//主键id

#define ORDER_PERSON_REQUIREMENT_GUID @"ORDER_PERSON_REQUIREMENT_GUID"//需求的GUID

#define ORDER_PERSON_USER_GUID @"ORDER_PERSON_USER_GUID"//预约人的guid

#define ORDER_PERSON_USER_NAME @"ORDER_PERSON_USER_NAME"//预约人的userName

#define ORDER_PERSON_USER_REALNAME @"ORDER_PERSON_USER_REALNAME"//预约人的真实姓名

#define ORDER_PERSON_USER_TYPE @"ORDER_PERSON_USER_TYPE"//预约人的用户类型,0中介，1为中介下的短工，2为私人

#define ORDER_PERSON_USER_SEX @"ORDER_PERSON_USER_SEX"//预约人的性别

#define ORDER_PERSON_USER_PHOTO @"ORDER_PERSON_USER_PHOTO"//预约人的头像

#define ORDER_PERSON_USER_EVALUATE @"ORDER_PERSON_USER_EVALUATE"//他的星级

#define ORDER_PERSON_USER_PHONE_NUMBER @"ORDER_PERSON_USER_PHONE_NUMBER"//联系电话

#define ORDER_PERSON_USER_TAG @"ORDER_PERSON_USER_TAG"//预约人的标签

#define ORDER_PERSON_QUOTE @"ORDER_PERSON_QUOTE"//预约人的报价

#define ORDER_PERSON_USER_SERVICE_COUNT @"ORDER_PERSON_USER_SERVICE_COUNT"//预约人的接活次数

#define ORDER_PERSON_YZ_TIME @"ORDER_PERSON_YZ_TIME"//预约人的抢单时间

#define ORDER_PERSON_COMPANY_USER_GUID @"ORDER_PERSON_COMPANY_USER_GUID"//预约人所属公司的guid

#define ORDER_PERSON_COMPANY_USER_NAME @"ORDER_PERSON_COMPANY_USER_NAME"//预约人所属公司的username

#define ORDER_PERSON_COMPANY_USER_REALNAME @"ORDER_PERSON_COMPANY_USER_REALNAME"//预约人所属公司的userRealName

#define ORDER_PERSON_COMPANY_USER_PHOTO @"ORDER_PERSON_COMPANY_USER_PHOTO"//预约人所属公司的头像

#define ORDER_PERSON_COMPANY_PHONE @"ORDER_PERSON_COMPANY_PHONE"//公司的电话

#define ORDER_PERSON_COMPANY_USER_ANNEAR @"ORDER_PERSON_COMPANY_USER_ANNEAR"//中介的锤炼号


//订单中的优惠券表
#define ORDER_COUPON @"ORDER_COUPON"//预约优惠券表
#define ORDER_COUPON_ID @"ORDER_COUPON_ID"
#define ORDER_COUPON_REQUIREMENTGUID @"ORDER_COUPON_REQUIREMENTGUID"//需求的guid
#define ORDER_COUPON_GUID @"ORDER_COUPON_GUID" //优惠券的guid
#define ORDER_COUPON_TYPE @"ORDER_COUPON_TYPE" //优惠券的类型
#define ORDER_COUPON_TITLE @"ORDER_COUPON_TITLE" //优惠券的标题
#define ORDER_COUPON_DETAIL @"ORDER_COUPON_DETAIL"//优惠券的使用说明
#define ORDER_COUPON_NUMBER @"ORDER_COUPON_NUMBER"//优惠券序列号
#define ORDER_COUPON_ENDTIME @"ORDER_COUPON_ENDTIME" //优惠券有效日期
#define ORDER_COUPON_USEDTIME @"ORDER_COUPON_USEDTIME" //优惠券的使用日期
#define ORDER_COUPON_SUITWORK @"ORDER_COUPON_SUITWORK" //优惠券适用工种
#define ORDER_COUPON_SUITWORK_TYPE @"ORDER_COUPON_SUITWORK_TYPE" //优惠券使用的工种，类型1，全部
#define ORDER_COUPON_SUITCOMPANY_TYPE @"ORDER_COUPON_SUITCOMPANY_TYPE" //优惠券使用商家类型，1全部
#define ORDER_COUPON_PULLPRICE @"ORDER_COUPON_PULLPRICE" //满多少
#define ORDER_COUPON_CUTPRICE @"ORDER_COUPON_CUTPRICE" // 抵消价格


//评价表

#define EVALUATE @"EVALUATE"

#define EVALUATE_REQUIREMENT_GUID @"EVALUATE_REQUIREMENT_GUID"//需求的guid

#define EVALUATE_FOR_EMPLOYEE @"EVALUATE_FOR_EMPLOYEE"//对雇主的整体评价

#define EVALUATE_FOR_EMPLOYEE_OTHER @"EVALUATE_FOR_EMPLOYEE_OTHER"//其他评价

#define EVALUATE_SERVE_QUALITY @"EVALUATE_SERVE_QUALITY"//质量评价

#define EVALUATE_SERVE_ATTITUDE @"EVALUATE_SERVE_ATTITUDE"//态度

#define EVALUATE_SERVE_SPEED @"EVALUATE_SERVE_SPEED"//速度

#define EVALUATE_FOR_EMPLOYEE_TIME @"EVALUATE_FOR_EMPLOYEE_TIME"//时间

#define EVALUATE_FOR_EMPLOYER @"EVALUATE_FOR_EMPLOYER"

#define EVALUATE_FOR_EMPLOYER_OTHER @"EVALUATE_FOR_EMPLOYER_OTHER"

#define EVALUATE_FOR_EMPLOYER_TIME @"EVALUATE_FOR_EMPLOYER_TIME"

//搜索记录表
#define SEARCHMARK @"SEARCHMARK"

#define SEARCHMARK_ID @"SEARCHMARK_ID"

#define SEARCHMARK_MESSAGE @"SEARCHMARK_MESSAGE"


#endif
